---
# splunk_config.yml
plugin: splunk-platform-automator

virtualbox:
#  box: "centos/7" # Default
#  box: "ubuntu/xenial64"
  memory: 1024
  cpus: 2
  vm:
    network: '"forwarded_port", guest: 8000, host: 8000'

# Issues:
# - solved: vbox needs 1024 mb ram for Splunk
# - solved: python must be installed
# - solved: selinux must be disabled
# - graphics device sometimes breaks boot (working config: display-server disabled, device=VMSVGA, ram=16MB)
# - first reboot of splunkd seems to hang, after the splunk_software role, in: RUNNING HANDLER [splunk_common : restart splunk]
#   workaround: reboot the VM and start the ansible run again
# - need to add port forwarding in vagrant: 8000 to 8000, but can do that for only one vm of course!
#   workaround: add port forward by hand in vbox

# DV: The os section needs to be customized:
os:
  # Used at Vagrant provisioning time to install python:
  #remote_command: 'which python || (sudo dnf update; sudo dnf install -y python39)'
  remote_command: |
    dnf update &&
    dnf install -y python39 &&
    setenforce 0 &&
    sed -i s/enforcing/disabled/g /etc/selinux/config
  # Used as a host var when running ansible:
  # but that still does not work because of the python selinux package that is missing
  # and is hard to install => workaround see above
  disable_selinux: true

# Splunk default settings
splunk_defaults:
  # splunk_env_name: splk
  # splunk_version: '8.2.3'
  # splunk_architecture: amd64
  # splunk_admin_password: 'splunklab'
  # splunk_license_file: Splunk_Enterprise.lic
  # splunk_indexes:
  #   test1:
  #   test2_metrics:
  #     datatype: metric

# Splunk hosts with its settings
splunk_hosts:
  # Indexer and Search Head on single node
  - name: shidx
    roles:
      - indexer
      - search_head

   # Universal Forwarder
#  - name: uf
#    roles:
#      - universal_forwarder
